//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test.Mediation {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Mediation.MediationSoap")]
    public interface MediationSoap {
        
        // CODEGEN: Generating message contract since element name data from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addUser", ReplyAction="*")]
        Test.Mediation.addUserResponse addUser(Test.Mediation.addUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.Mediation.addUserResponse> addUserAsync(Test.Mediation.addUserRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fileRequest", ReplyAction="*")]
        Test.Mediation.fileRequestResponse fileRequest(Test.Mediation.fileRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fileRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.Mediation.fileRequestResponse> fileRequestAsync(Test.Mediation.fileRequestRequest request);
        
        // CODEGEN: Generating message contract since element name getFilesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFiles", ReplyAction="*")]
        Test.Mediation.getFilesResponse getFiles(Test.Mediation.getFilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFiles", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.Mediation.getFilesResponse> getFilesAsync(Test.Mediation.getFilesRequest request);
        
        // CODEGEN: Generating message contract since element name getUsersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUsers", ReplyAction="*")]
        Test.Mediation.getUsersResponse getUsers(Test.Mediation.getUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.Mediation.getUsersResponse> getUsersAsync(Test.Mediation.getUsersRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        Test.Mediation.loginResponse login(Test.Mediation.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.Mediation.loginResponse> loginAsync(Test.Mediation.loginRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logout", ReplyAction="*")]
        Test.Mediation.logoutResponse logout(Test.Mediation.logoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logout", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.Mediation.logoutResponse> logoutAsync(Test.Mediation.logoutRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/removeUser", ReplyAction="*")]
        Test.Mediation.removeUserResponse removeUser(Test.Mediation.removeUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/removeUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.Mediation.removeUserResponse> removeUserAsync(Test.Mediation.removeUserRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateUser", ReplyAction="*")]
        Test.Mediation.updateUserResponse updateUser(Test.Mediation.updateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Test.Mediation.updateUserResponse> updateUserAsync(Test.Mediation.updateUserRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addUser", Namespace="http://tempuri.org/", Order=0)]
        public Test.Mediation.addUserRequestBody Body;
        
        public addUserRequest() {
        }
        
        public addUserRequest(Test.Mediation.addUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string data;
        
        public addUserRequestBody() {
        }
        
        public addUserRequestBody(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.Mediation.addUserResponseBody Body;
        
        public addUserResponse() {
        }
        
        public addUserResponse(Test.Mediation.addUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addUserResult;
        
        public addUserResponseBody() {
        }
        
        public addUserResponseBody(string addUserResult) {
            this.addUserResult = addUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fileRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fileRequest", Namespace="http://tempuri.org/", Order=0)]
        public Test.Mediation.fileRequestRequestBody Body;
        
        public fileRequestRequest() {
        }
        
        public fileRequestRequest(Test.Mediation.fileRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fileRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string data;
        
        public fileRequestRequestBody() {
        }
        
        public fileRequestRequestBody(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fileRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fileRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.Mediation.fileRequestResponseBody Body;
        
        public fileRequestResponse() {
        }
        
        public fileRequestResponse(Test.Mediation.fileRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fileRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileRequestResult;
        
        public fileRequestResponseBody() {
        }
        
        public fileRequestResponseBody(string fileRequestResult) {
            this.fileRequestResult = fileRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFiles", Namespace="http://tempuri.org/", Order=0)]
        public Test.Mediation.getFilesRequestBody Body;
        
        public getFilesRequest() {
        }
        
        public getFilesRequest(Test.Mediation.getFilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getFilesRequestBody {
        
        public getFilesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFilesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.Mediation.getFilesResponseBody Body;
        
        public getFilesResponse() {
        }
        
        public getFilesResponse(Test.Mediation.getFilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getFilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getFilesResult;
        
        public getFilesResponseBody() {
        }
        
        public getFilesResponseBody(string getFilesResult) {
            this.getFilesResult = getFilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUsers", Namespace="http://tempuri.org/", Order=0)]
        public Test.Mediation.getUsersRequestBody Body;
        
        public getUsersRequest() {
        }
        
        public getUsersRequest(Test.Mediation.getUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getUsersRequestBody {
        
        public getUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.Mediation.getUsersResponseBody Body;
        
        public getUsersResponse() {
        }
        
        public getUsersResponse(Test.Mediation.getUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUsersResult;
        
        public getUsersResponseBody() {
        }
        
        public getUsersResponseBody(string getUsersResult) {
            this.getUsersResult = getUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://tempuri.org/", Order=0)]
        public Test.Mediation.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(Test.Mediation.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string data;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.Mediation.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(Test.Mediation.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginResult;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string loginResult) {
            this.loginResult = loginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logout", Namespace="http://tempuri.org/", Order=0)]
        public Test.Mediation.logoutRequestBody Body;
        
        public logoutRequest() {
        }
        
        public logoutRequest(Test.Mediation.logoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string data;
        
        public logoutRequestBody() {
        }
        
        public logoutRequestBody(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logoutResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.Mediation.logoutResponseBody Body;
        
        public logoutResponse() {
        }
        
        public logoutResponse(Test.Mediation.logoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logoutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string logoutResult;
        
        public logoutResponseBody() {
        }
        
        public logoutResponseBody(string logoutResult) {
            this.logoutResult = logoutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="removeUser", Namespace="http://tempuri.org/", Order=0)]
        public Test.Mediation.removeUserRequestBody Body;
        
        public removeUserRequest() {
        }
        
        public removeUserRequest(Test.Mediation.removeUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class removeUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string data;
        
        public removeUserRequestBody() {
        }
        
        public removeUserRequestBody(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="removeUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.Mediation.removeUserResponseBody Body;
        
        public removeUserResponse() {
        }
        
        public removeUserResponse(Test.Mediation.removeUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class removeUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string removeUserResult;
        
        public removeUserResponseBody() {
        }
        
        public removeUserResponseBody(string removeUserResult) {
            this.removeUserResult = removeUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateUser", Namespace="http://tempuri.org/", Order=0)]
        public Test.Mediation.updateUserRequestBody Body;
        
        public updateUserRequest() {
        }
        
        public updateUserRequest(Test.Mediation.updateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string data;
        
        public updateUserRequestBody() {
        }
        
        public updateUserRequestBody(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Test.Mediation.updateUserResponseBody Body;
        
        public updateUserResponse() {
        }
        
        public updateUserResponse(Test.Mediation.updateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string updateUserResult;
        
        public updateUserResponseBody() {
        }
        
        public updateUserResponseBody(string updateUserResult) {
            this.updateUserResult = updateUserResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MediationSoapChannel : Test.Mediation.MediationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MediationSoapClient : System.ServiceModel.ClientBase<Test.Mediation.MediationSoap>, Test.Mediation.MediationSoap {
        
        public MediationSoapClient() {
        }
        
        public MediationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MediationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MediationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MediationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.Mediation.addUserResponse Test.Mediation.MediationSoap.addUser(Test.Mediation.addUserRequest request) {
            return base.Channel.addUser(request);
        }
        
        public string addUser(string data) {
            Test.Mediation.addUserRequest inValue = new Test.Mediation.addUserRequest();
            inValue.Body = new Test.Mediation.addUserRequestBody();
            inValue.Body.data = data;
            Test.Mediation.addUserResponse retVal = ((Test.Mediation.MediationSoap)(this)).addUser(inValue);
            return retVal.Body.addUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.Mediation.addUserResponse> Test.Mediation.MediationSoap.addUserAsync(Test.Mediation.addUserRequest request) {
            return base.Channel.addUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.Mediation.addUserResponse> addUserAsync(string data) {
            Test.Mediation.addUserRequest inValue = new Test.Mediation.addUserRequest();
            inValue.Body = new Test.Mediation.addUserRequestBody();
            inValue.Body.data = data;
            return ((Test.Mediation.MediationSoap)(this)).addUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.Mediation.fileRequestResponse Test.Mediation.MediationSoap.fileRequest(Test.Mediation.fileRequestRequest request) {
            return base.Channel.fileRequest(request);
        }
        
        public string fileRequest(string data) {
            Test.Mediation.fileRequestRequest inValue = new Test.Mediation.fileRequestRequest();
            inValue.Body = new Test.Mediation.fileRequestRequestBody();
            inValue.Body.data = data;
            Test.Mediation.fileRequestResponse retVal = ((Test.Mediation.MediationSoap)(this)).fileRequest(inValue);
            return retVal.Body.fileRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.Mediation.fileRequestResponse> Test.Mediation.MediationSoap.fileRequestAsync(Test.Mediation.fileRequestRequest request) {
            return base.Channel.fileRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.Mediation.fileRequestResponse> fileRequestAsync(string data) {
            Test.Mediation.fileRequestRequest inValue = new Test.Mediation.fileRequestRequest();
            inValue.Body = new Test.Mediation.fileRequestRequestBody();
            inValue.Body.data = data;
            return ((Test.Mediation.MediationSoap)(this)).fileRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.Mediation.getFilesResponse Test.Mediation.MediationSoap.getFiles(Test.Mediation.getFilesRequest request) {
            return base.Channel.getFiles(request);
        }
        
        public string getFiles() {
            Test.Mediation.getFilesRequest inValue = new Test.Mediation.getFilesRequest();
            inValue.Body = new Test.Mediation.getFilesRequestBody();
            Test.Mediation.getFilesResponse retVal = ((Test.Mediation.MediationSoap)(this)).getFiles(inValue);
            return retVal.Body.getFilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.Mediation.getFilesResponse> Test.Mediation.MediationSoap.getFilesAsync(Test.Mediation.getFilesRequest request) {
            return base.Channel.getFilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.Mediation.getFilesResponse> getFilesAsync() {
            Test.Mediation.getFilesRequest inValue = new Test.Mediation.getFilesRequest();
            inValue.Body = new Test.Mediation.getFilesRequestBody();
            return ((Test.Mediation.MediationSoap)(this)).getFilesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.Mediation.getUsersResponse Test.Mediation.MediationSoap.getUsers(Test.Mediation.getUsersRequest request) {
            return base.Channel.getUsers(request);
        }
        
        public string getUsers() {
            Test.Mediation.getUsersRequest inValue = new Test.Mediation.getUsersRequest();
            inValue.Body = new Test.Mediation.getUsersRequestBody();
            Test.Mediation.getUsersResponse retVal = ((Test.Mediation.MediationSoap)(this)).getUsers(inValue);
            return retVal.Body.getUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.Mediation.getUsersResponse> Test.Mediation.MediationSoap.getUsersAsync(Test.Mediation.getUsersRequest request) {
            return base.Channel.getUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.Mediation.getUsersResponse> getUsersAsync() {
            Test.Mediation.getUsersRequest inValue = new Test.Mediation.getUsersRequest();
            inValue.Body = new Test.Mediation.getUsersRequestBody();
            return ((Test.Mediation.MediationSoap)(this)).getUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.Mediation.loginResponse Test.Mediation.MediationSoap.login(Test.Mediation.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public string login(string data) {
            Test.Mediation.loginRequest inValue = new Test.Mediation.loginRequest();
            inValue.Body = new Test.Mediation.loginRequestBody();
            inValue.Body.data = data;
            Test.Mediation.loginResponse retVal = ((Test.Mediation.MediationSoap)(this)).login(inValue);
            return retVal.Body.loginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.Mediation.loginResponse> Test.Mediation.MediationSoap.loginAsync(Test.Mediation.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.Mediation.loginResponse> loginAsync(string data) {
            Test.Mediation.loginRequest inValue = new Test.Mediation.loginRequest();
            inValue.Body = new Test.Mediation.loginRequestBody();
            inValue.Body.data = data;
            return ((Test.Mediation.MediationSoap)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.Mediation.logoutResponse Test.Mediation.MediationSoap.logout(Test.Mediation.logoutRequest request) {
            return base.Channel.logout(request);
        }
        
        public string logout(string data) {
            Test.Mediation.logoutRequest inValue = new Test.Mediation.logoutRequest();
            inValue.Body = new Test.Mediation.logoutRequestBody();
            inValue.Body.data = data;
            Test.Mediation.logoutResponse retVal = ((Test.Mediation.MediationSoap)(this)).logout(inValue);
            return retVal.Body.logoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.Mediation.logoutResponse> Test.Mediation.MediationSoap.logoutAsync(Test.Mediation.logoutRequest request) {
            return base.Channel.logoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.Mediation.logoutResponse> logoutAsync(string data) {
            Test.Mediation.logoutRequest inValue = new Test.Mediation.logoutRequest();
            inValue.Body = new Test.Mediation.logoutRequestBody();
            inValue.Body.data = data;
            return ((Test.Mediation.MediationSoap)(this)).logoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.Mediation.removeUserResponse Test.Mediation.MediationSoap.removeUser(Test.Mediation.removeUserRequest request) {
            return base.Channel.removeUser(request);
        }
        
        public string removeUser(string data) {
            Test.Mediation.removeUserRequest inValue = new Test.Mediation.removeUserRequest();
            inValue.Body = new Test.Mediation.removeUserRequestBody();
            inValue.Body.data = data;
            Test.Mediation.removeUserResponse retVal = ((Test.Mediation.MediationSoap)(this)).removeUser(inValue);
            return retVal.Body.removeUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.Mediation.removeUserResponse> Test.Mediation.MediationSoap.removeUserAsync(Test.Mediation.removeUserRequest request) {
            return base.Channel.removeUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.Mediation.removeUserResponse> removeUserAsync(string data) {
            Test.Mediation.removeUserRequest inValue = new Test.Mediation.removeUserRequest();
            inValue.Body = new Test.Mediation.removeUserRequestBody();
            inValue.Body.data = data;
            return ((Test.Mediation.MediationSoap)(this)).removeUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Test.Mediation.updateUserResponse Test.Mediation.MediationSoap.updateUser(Test.Mediation.updateUserRequest request) {
            return base.Channel.updateUser(request);
        }
        
        public string updateUser(string data) {
            Test.Mediation.updateUserRequest inValue = new Test.Mediation.updateUserRequest();
            inValue.Body = new Test.Mediation.updateUserRequestBody();
            inValue.Body.data = data;
            Test.Mediation.updateUserResponse retVal = ((Test.Mediation.MediationSoap)(this)).updateUser(inValue);
            return retVal.Body.updateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Test.Mediation.updateUserResponse> Test.Mediation.MediationSoap.updateUserAsync(Test.Mediation.updateUserRequest request) {
            return base.Channel.updateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Test.Mediation.updateUserResponse> updateUserAsync(string data) {
            Test.Mediation.updateUserRequest inValue = new Test.Mediation.updateUserRequest();
            inValue.Body = new Test.Mediation.updateUserRequestBody();
            inValue.Body.data = data;
            return ((Test.Mediation.MediationSoap)(this)).updateUserAsync(inValue);
        }
    }
}
