//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.Mediation {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Mediation.MediationSoap")]
    public interface MediationSoap {
        
        // CODEGEN: Generating message contract since element name data from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addUser", ReplyAction="*")]
        Client.Mediation.addUserResponse addUser(Client.Mediation.addUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.Mediation.addUserResponse> addUserAsync(Client.Mediation.addUserRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/removeUser", ReplyAction="*")]
        Client.Mediation.removeUserResponse removeUser(Client.Mediation.removeUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/removeUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.Mediation.removeUserResponse> removeUserAsync(Client.Mediation.removeUserRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateUser", ReplyAction="*")]
        Client.Mediation.updateUserResponse updateUser(Client.Mediation.updateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/updateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.Mediation.updateUserResponse> updateUserAsync(Client.Mediation.updateUserRequest request);
        
        // CODEGEN: Generating message contract since element name userData from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        Client.Mediation.loginResponse login(Client.Mediation.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/login", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.Mediation.loginResponse> loginAsync(Client.Mediation.loginRequest request);
        
        // CODEGEN: Generating message contract since element name userData from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logout", ReplyAction="*")]
        Client.Mediation.logoutResponse logout(Client.Mediation.logoutRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/logout", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.Mediation.logoutResponse> logoutAsync(Client.Mediation.logoutRequest request);
        
        // CODEGEN: Generating message contract since element name userData from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fileRequest", ReplyAction="*")]
        Client.Mediation.fileRequestResponse fileRequest(Client.Mediation.fileRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/fileRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.Mediation.fileRequestResponse> fileRequestAsync(Client.Mediation.fileRequestRequest request);
        
        // CODEGEN: Generating message contract since element name getFilesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFiles", ReplyAction="*")]
        Client.Mediation.getFilesResponse getFiles(Client.Mediation.getFilesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getFiles", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.Mediation.getFilesResponse> getFilesAsync(Client.Mediation.getFilesRequest request);
        
        // CODEGEN: Generating message contract since element name getUsersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUsers", ReplyAction="*")]
        Client.Mediation.getUsersResponse getUsers(Client.Mediation.getUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.Mediation.getUsersResponse> getUsersAsync(Client.Mediation.getUsersRequest request);
        
        // CODEGEN: Generating message contract since element name getActiveUsersResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getActiveUsers", ReplyAction="*")]
        Client.Mediation.getActiveUsersResponse getActiveUsers(Client.Mediation.getActiveUsersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/getActiveUsers", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.Mediation.getActiveUsersResponse> getActiveUsersAsync(Client.Mediation.getActiveUsersRequest request);
        
        // CODEGEN: Generating message contract since element name data from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isAdmin", ReplyAction="*")]
        Client.Mediation.isAdminResponse isAdmin(Client.Mediation.isAdminRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/isAdmin", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.Mediation.isAdminResponse> isAdminAsync(Client.Mediation.isAdminRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enable", ReplyAction="*")]
        Client.Mediation.enableResponse enable(Client.Mediation.enableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/enable", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.Mediation.enableResponse> enableAsync(Client.Mediation.enableRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/disable", ReplyAction="*")]
        Client.Mediation.disableResponse disable(Client.Mediation.disableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/disable", ReplyAction="*")]
        System.Threading.Tasks.Task<Client.Mediation.disableResponse> disableAsync(Client.Mediation.disableRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteAllFiles", ReplyAction="*")]
        void deleteAllFiles();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/deleteAllFiles", ReplyAction="*")]
        System.Threading.Tasks.Task deleteAllFilesAsync();
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addUser", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.addUserRequestBody Body;
        
        public addUserRequest() {
        }
        
        public addUserRequest(Client.Mediation.addUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string data;
        
        public addUserRequestBody() {
        }
        
        public addUserRequestBody(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class addUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="addUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.addUserResponseBody Body;
        
        public addUserResponse() {
        }
        
        public addUserResponse(Client.Mediation.addUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class addUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string addUserResult;
        
        public addUserResponseBody() {
        }
        
        public addUserResponseBody(string addUserResult) {
            this.addUserResult = addUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="removeUser", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.removeUserRequestBody Body;
        
        public removeUserRequest() {
        }
        
        public removeUserRequest(Client.Mediation.removeUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class removeUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string data;
        
        public removeUserRequestBody() {
        }
        
        public removeUserRequestBody(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class removeUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="removeUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.removeUserResponseBody Body;
        
        public removeUserResponse() {
        }
        
        public removeUserResponse(Client.Mediation.removeUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class removeUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string removeUserResult;
        
        public removeUserResponseBody() {
        }
        
        public removeUserResponseBody(string removeUserResult) {
            this.removeUserResult = removeUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateUser", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.updateUserRequestBody Body;
        
        public updateUserRequest() {
        }
        
        public updateUserRequest(Client.Mediation.updateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string data;
        
        public updateUserRequestBody() {
        }
        
        public updateUserRequestBody(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class updateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="updateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.updateUserResponseBody Body;
        
        public updateUserResponse() {
        }
        
        public updateUserResponse(Client.Mediation.updateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class updateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string updateUserResult;
        
        public updateUserResponseBody() {
        }
        
        public updateUserResponseBody(string updateUserResult) {
            this.updateUserResult = updateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(Client.Mediation.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string filesData;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string userData, string filesData) {
            this.userData = userData;
            this.filesData = filesData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(Client.Mediation.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string loginResult;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(string loginResult) {
            this.loginResult = loginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoutRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logout", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.logoutRequestBody Body;
        
        public logoutRequest() {
        }
        
        public logoutRequest(Client.Mediation.logoutRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logoutRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string filesData;
        
        public logoutRequestBody() {
        }
        
        public logoutRequestBody(string userData, string filesData) {
            this.userData = userData;
            this.filesData = filesData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class logoutResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="logoutResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.logoutResponseBody Body;
        
        public logoutResponse() {
        }
        
        public logoutResponse(Client.Mediation.logoutResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class logoutResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string logoutResult;
        
        public logoutResponseBody() {
        }
        
        public logoutResponseBody(string logoutResult) {
            this.logoutResult = logoutResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fileRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fileRequest", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.fileRequestRequestBody Body;
        
        public fileRequestRequest() {
        }
        
        public fileRequestRequest(Client.Mediation.fileRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fileRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userData;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fileData;
        
        public fileRequestRequestBody() {
        }
        
        public fileRequestRequestBody(string userData, string fileData) {
            this.userData = userData;
            this.fileData = fileData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fileRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fileRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.fileRequestResponseBody Body;
        
        public fileRequestResponse() {
        }
        
        public fileRequestResponse(Client.Mediation.fileRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class fileRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fileRequestResult;
        
        public fileRequestResponseBody() {
        }
        
        public fileRequestResponseBody(string fileRequestResult) {
            this.fileRequestResult = fileRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFilesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFiles", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.getFilesRequestBody Body;
        
        public getFilesRequest() {
        }
        
        public getFilesRequest(Client.Mediation.getFilesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getFilesRequestBody {
        
        public getFilesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getFilesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getFilesResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.getFilesResponseBody Body;
        
        public getFilesResponse() {
        }
        
        public getFilesResponse(Client.Mediation.getFilesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getFilesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getFilesResult;
        
        public getFilesResponseBody() {
        }
        
        public getFilesResponseBody(string getFilesResult) {
            this.getFilesResult = getFilesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUsers", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.getUsersRequestBody Body;
        
        public getUsersRequest() {
        }
        
        public getUsersRequest(Client.Mediation.getUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getUsersRequestBody {
        
        public getUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.getUsersResponseBody Body;
        
        public getUsersResponse() {
        }
        
        public getUsersResponse(Client.Mediation.getUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getUsersResult;
        
        public getUsersResponseBody() {
        }
        
        public getUsersResponseBody(string getUsersResult) {
            this.getUsersResult = getUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getActiveUsersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getActiveUsers", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.getActiveUsersRequestBody Body;
        
        public getActiveUsersRequest() {
        }
        
        public getActiveUsersRequest(Client.Mediation.getActiveUsersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class getActiveUsersRequestBody {
        
        public getActiveUsersRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getActiveUsersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="getActiveUsersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.getActiveUsersResponseBody Body;
        
        public getActiveUsersResponse() {
        }
        
        public getActiveUsersResponse(Client.Mediation.getActiveUsersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class getActiveUsersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string getActiveUsersResult;
        
        public getActiveUsersResponseBody() {
        }
        
        public getActiveUsersResponseBody(string getActiveUsersResult) {
            this.getActiveUsersResult = getActiveUsersResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isAdmin", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.isAdminRequestBody Body;
        
        public isAdminRequest() {
        }
        
        public isAdminRequest(Client.Mediation.isAdminRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isAdminRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string data;
        
        public isAdminRequestBody() {
        }
        
        public isAdminRequestBody(string data) {
            this.data = data;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class isAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="isAdminResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.isAdminResponseBody Body;
        
        public isAdminResponse() {
        }
        
        public isAdminResponse(Client.Mediation.isAdminResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class isAdminResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string isAdminResult;
        
        public isAdminResponseBody() {
        }
        
        public isAdminResponseBody(string isAdminResult) {
            this.isAdminResult = isAdminResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="enable", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.enableRequestBody Body;
        
        public enableRequest() {
        }
        
        public enableRequest(Client.Mediation.enableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class enableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public enableRequestBody() {
        }
        
        public enableRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class enableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="enableResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.enableResponseBody Body;
        
        public enableResponse() {
        }
        
        public enableResponse(Client.Mediation.enableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class enableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string enableResult;
        
        public enableResponseBody() {
        }
        
        public enableResponseBody(string enableResult) {
            this.enableResult = enableResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class disableRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="disable", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.disableRequestBody Body;
        
        public disableRequest() {
        }
        
        public disableRequest(Client.Mediation.disableRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class disableRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public disableRequestBody() {
        }
        
        public disableRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class disableResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="disableResponse", Namespace="http://tempuri.org/", Order=0)]
        public Client.Mediation.disableResponseBody Body;
        
        public disableResponse() {
        }
        
        public disableResponse(Client.Mediation.disableResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class disableResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string disableResult;
        
        public disableResponseBody() {
        }
        
        public disableResponseBody(string disableResult) {
            this.disableResult = disableResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MediationSoapChannel : Client.Mediation.MediationSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MediationSoapClient : System.ServiceModel.ClientBase<Client.Mediation.MediationSoap>, Client.Mediation.MediationSoap {
        
        public MediationSoapClient() {
        }
        
        public MediationSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MediationSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MediationSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MediationSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Mediation.addUserResponse Client.Mediation.MediationSoap.addUser(Client.Mediation.addUserRequest request) {
            return base.Channel.addUser(request);
        }
        
        public string addUser(string data) {
            Client.Mediation.addUserRequest inValue = new Client.Mediation.addUserRequest();
            inValue.Body = new Client.Mediation.addUserRequestBody();
            inValue.Body.data = data;
            Client.Mediation.addUserResponse retVal = ((Client.Mediation.MediationSoap)(this)).addUser(inValue);
            return retVal.Body.addUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Mediation.addUserResponse> Client.Mediation.MediationSoap.addUserAsync(Client.Mediation.addUserRequest request) {
            return base.Channel.addUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Mediation.addUserResponse> addUserAsync(string data) {
            Client.Mediation.addUserRequest inValue = new Client.Mediation.addUserRequest();
            inValue.Body = new Client.Mediation.addUserRequestBody();
            inValue.Body.data = data;
            return ((Client.Mediation.MediationSoap)(this)).addUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Mediation.removeUserResponse Client.Mediation.MediationSoap.removeUser(Client.Mediation.removeUserRequest request) {
            return base.Channel.removeUser(request);
        }
        
        public string removeUser(string data) {
            Client.Mediation.removeUserRequest inValue = new Client.Mediation.removeUserRequest();
            inValue.Body = new Client.Mediation.removeUserRequestBody();
            inValue.Body.data = data;
            Client.Mediation.removeUserResponse retVal = ((Client.Mediation.MediationSoap)(this)).removeUser(inValue);
            return retVal.Body.removeUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Mediation.removeUserResponse> Client.Mediation.MediationSoap.removeUserAsync(Client.Mediation.removeUserRequest request) {
            return base.Channel.removeUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Mediation.removeUserResponse> removeUserAsync(string data) {
            Client.Mediation.removeUserRequest inValue = new Client.Mediation.removeUserRequest();
            inValue.Body = new Client.Mediation.removeUserRequestBody();
            inValue.Body.data = data;
            return ((Client.Mediation.MediationSoap)(this)).removeUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Mediation.updateUserResponse Client.Mediation.MediationSoap.updateUser(Client.Mediation.updateUserRequest request) {
            return base.Channel.updateUser(request);
        }
        
        public string updateUser(string data) {
            Client.Mediation.updateUserRequest inValue = new Client.Mediation.updateUserRequest();
            inValue.Body = new Client.Mediation.updateUserRequestBody();
            inValue.Body.data = data;
            Client.Mediation.updateUserResponse retVal = ((Client.Mediation.MediationSoap)(this)).updateUser(inValue);
            return retVal.Body.updateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Mediation.updateUserResponse> Client.Mediation.MediationSoap.updateUserAsync(Client.Mediation.updateUserRequest request) {
            return base.Channel.updateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Mediation.updateUserResponse> updateUserAsync(string data) {
            Client.Mediation.updateUserRequest inValue = new Client.Mediation.updateUserRequest();
            inValue.Body = new Client.Mediation.updateUserRequestBody();
            inValue.Body.data = data;
            return ((Client.Mediation.MediationSoap)(this)).updateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Mediation.loginResponse Client.Mediation.MediationSoap.login(Client.Mediation.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public string login(string userData, string filesData) {
            Client.Mediation.loginRequest inValue = new Client.Mediation.loginRequest();
            inValue.Body = new Client.Mediation.loginRequestBody();
            inValue.Body.userData = userData;
            inValue.Body.filesData = filesData;
            Client.Mediation.loginResponse retVal = ((Client.Mediation.MediationSoap)(this)).login(inValue);
            return retVal.Body.loginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Mediation.loginResponse> Client.Mediation.MediationSoap.loginAsync(Client.Mediation.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Mediation.loginResponse> loginAsync(string userData, string filesData) {
            Client.Mediation.loginRequest inValue = new Client.Mediation.loginRequest();
            inValue.Body = new Client.Mediation.loginRequestBody();
            inValue.Body.userData = userData;
            inValue.Body.filesData = filesData;
            return ((Client.Mediation.MediationSoap)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Mediation.logoutResponse Client.Mediation.MediationSoap.logout(Client.Mediation.logoutRequest request) {
            return base.Channel.logout(request);
        }
        
        public string logout(string userData, string filesData) {
            Client.Mediation.logoutRequest inValue = new Client.Mediation.logoutRequest();
            inValue.Body = new Client.Mediation.logoutRequestBody();
            inValue.Body.userData = userData;
            inValue.Body.filesData = filesData;
            Client.Mediation.logoutResponse retVal = ((Client.Mediation.MediationSoap)(this)).logout(inValue);
            return retVal.Body.logoutResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Mediation.logoutResponse> Client.Mediation.MediationSoap.logoutAsync(Client.Mediation.logoutRequest request) {
            return base.Channel.logoutAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Mediation.logoutResponse> logoutAsync(string userData, string filesData) {
            Client.Mediation.logoutRequest inValue = new Client.Mediation.logoutRequest();
            inValue.Body = new Client.Mediation.logoutRequestBody();
            inValue.Body.userData = userData;
            inValue.Body.filesData = filesData;
            return ((Client.Mediation.MediationSoap)(this)).logoutAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Mediation.fileRequestResponse Client.Mediation.MediationSoap.fileRequest(Client.Mediation.fileRequestRequest request) {
            return base.Channel.fileRequest(request);
        }
        
        public string fileRequest(string userData, string fileData) {
            Client.Mediation.fileRequestRequest inValue = new Client.Mediation.fileRequestRequest();
            inValue.Body = new Client.Mediation.fileRequestRequestBody();
            inValue.Body.userData = userData;
            inValue.Body.fileData = fileData;
            Client.Mediation.fileRequestResponse retVal = ((Client.Mediation.MediationSoap)(this)).fileRequest(inValue);
            return retVal.Body.fileRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Mediation.fileRequestResponse> Client.Mediation.MediationSoap.fileRequestAsync(Client.Mediation.fileRequestRequest request) {
            return base.Channel.fileRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Mediation.fileRequestResponse> fileRequestAsync(string userData, string fileData) {
            Client.Mediation.fileRequestRequest inValue = new Client.Mediation.fileRequestRequest();
            inValue.Body = new Client.Mediation.fileRequestRequestBody();
            inValue.Body.userData = userData;
            inValue.Body.fileData = fileData;
            return ((Client.Mediation.MediationSoap)(this)).fileRequestAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Mediation.getFilesResponse Client.Mediation.MediationSoap.getFiles(Client.Mediation.getFilesRequest request) {
            return base.Channel.getFiles(request);
        }
        
        public string getFiles() {
            Client.Mediation.getFilesRequest inValue = new Client.Mediation.getFilesRequest();
            inValue.Body = new Client.Mediation.getFilesRequestBody();
            Client.Mediation.getFilesResponse retVal = ((Client.Mediation.MediationSoap)(this)).getFiles(inValue);
            return retVal.Body.getFilesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Mediation.getFilesResponse> Client.Mediation.MediationSoap.getFilesAsync(Client.Mediation.getFilesRequest request) {
            return base.Channel.getFilesAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Mediation.getFilesResponse> getFilesAsync() {
            Client.Mediation.getFilesRequest inValue = new Client.Mediation.getFilesRequest();
            inValue.Body = new Client.Mediation.getFilesRequestBody();
            return ((Client.Mediation.MediationSoap)(this)).getFilesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Mediation.getUsersResponse Client.Mediation.MediationSoap.getUsers(Client.Mediation.getUsersRequest request) {
            return base.Channel.getUsers(request);
        }
        
        public string getUsers() {
            Client.Mediation.getUsersRequest inValue = new Client.Mediation.getUsersRequest();
            inValue.Body = new Client.Mediation.getUsersRequestBody();
            Client.Mediation.getUsersResponse retVal = ((Client.Mediation.MediationSoap)(this)).getUsers(inValue);
            return retVal.Body.getUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Mediation.getUsersResponse> Client.Mediation.MediationSoap.getUsersAsync(Client.Mediation.getUsersRequest request) {
            return base.Channel.getUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Mediation.getUsersResponse> getUsersAsync() {
            Client.Mediation.getUsersRequest inValue = new Client.Mediation.getUsersRequest();
            inValue.Body = new Client.Mediation.getUsersRequestBody();
            return ((Client.Mediation.MediationSoap)(this)).getUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Mediation.getActiveUsersResponse Client.Mediation.MediationSoap.getActiveUsers(Client.Mediation.getActiveUsersRequest request) {
            return base.Channel.getActiveUsers(request);
        }
        
        public string getActiveUsers() {
            Client.Mediation.getActiveUsersRequest inValue = new Client.Mediation.getActiveUsersRequest();
            inValue.Body = new Client.Mediation.getActiveUsersRequestBody();
            Client.Mediation.getActiveUsersResponse retVal = ((Client.Mediation.MediationSoap)(this)).getActiveUsers(inValue);
            return retVal.Body.getActiveUsersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Mediation.getActiveUsersResponse> Client.Mediation.MediationSoap.getActiveUsersAsync(Client.Mediation.getActiveUsersRequest request) {
            return base.Channel.getActiveUsersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Mediation.getActiveUsersResponse> getActiveUsersAsync() {
            Client.Mediation.getActiveUsersRequest inValue = new Client.Mediation.getActiveUsersRequest();
            inValue.Body = new Client.Mediation.getActiveUsersRequestBody();
            return ((Client.Mediation.MediationSoap)(this)).getActiveUsersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Mediation.isAdminResponse Client.Mediation.MediationSoap.isAdmin(Client.Mediation.isAdminRequest request) {
            return base.Channel.isAdmin(request);
        }
        
        public string isAdmin(string data) {
            Client.Mediation.isAdminRequest inValue = new Client.Mediation.isAdminRequest();
            inValue.Body = new Client.Mediation.isAdminRequestBody();
            inValue.Body.data = data;
            Client.Mediation.isAdminResponse retVal = ((Client.Mediation.MediationSoap)(this)).isAdmin(inValue);
            return retVal.Body.isAdminResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Mediation.isAdminResponse> Client.Mediation.MediationSoap.isAdminAsync(Client.Mediation.isAdminRequest request) {
            return base.Channel.isAdminAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Mediation.isAdminResponse> isAdminAsync(string data) {
            Client.Mediation.isAdminRequest inValue = new Client.Mediation.isAdminRequest();
            inValue.Body = new Client.Mediation.isAdminRequestBody();
            inValue.Body.data = data;
            return ((Client.Mediation.MediationSoap)(this)).isAdminAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Mediation.enableResponse Client.Mediation.MediationSoap.enable(Client.Mediation.enableRequest request) {
            return base.Channel.enable(request);
        }
        
        public string enable(string name) {
            Client.Mediation.enableRequest inValue = new Client.Mediation.enableRequest();
            inValue.Body = new Client.Mediation.enableRequestBody();
            inValue.Body.name = name;
            Client.Mediation.enableResponse retVal = ((Client.Mediation.MediationSoap)(this)).enable(inValue);
            return retVal.Body.enableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Mediation.enableResponse> Client.Mediation.MediationSoap.enableAsync(Client.Mediation.enableRequest request) {
            return base.Channel.enableAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Mediation.enableResponse> enableAsync(string name) {
            Client.Mediation.enableRequest inValue = new Client.Mediation.enableRequest();
            inValue.Body = new Client.Mediation.enableRequestBody();
            inValue.Body.name = name;
            return ((Client.Mediation.MediationSoap)(this)).enableAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.Mediation.disableResponse Client.Mediation.MediationSoap.disable(Client.Mediation.disableRequest request) {
            return base.Channel.disable(request);
        }
        
        public string disable(string name) {
            Client.Mediation.disableRequest inValue = new Client.Mediation.disableRequest();
            inValue.Body = new Client.Mediation.disableRequestBody();
            inValue.Body.name = name;
            Client.Mediation.disableResponse retVal = ((Client.Mediation.MediationSoap)(this)).disable(inValue);
            return retVal.Body.disableResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Client.Mediation.disableResponse> Client.Mediation.MediationSoap.disableAsync(Client.Mediation.disableRequest request) {
            return base.Channel.disableAsync(request);
        }
        
        public System.Threading.Tasks.Task<Client.Mediation.disableResponse> disableAsync(string name) {
            Client.Mediation.disableRequest inValue = new Client.Mediation.disableRequest();
            inValue.Body = new Client.Mediation.disableRequestBody();
            inValue.Body.name = name;
            return ((Client.Mediation.MediationSoap)(this)).disableAsync(inValue);
        }
        
        public void deleteAllFiles() {
            base.Channel.deleteAllFiles();
        }
        
        public System.Threading.Tasks.Task deleteAllFilesAsync() {
            return base.Channel.deleteAllFilesAsync();
        }
    }
}
